
NAME_POOL = ["Aunty Sarah", "Cheow Chi Bay", "Muhammad Amirul Hafiz", "Chong Bing Heng", "Lim Jing Xiang",
             "Lum Jun Xiang", "Darren", "Siti", "Kennedy Leon", "Encik Firdhaus", "Mick", "Aguindo Mio","Ito aiko",
             "Nguyen Thanh Son", "Franklin", "Erik", "Ly Mai", "Jennie","Luis","William Bennett","Charlotte","Kim Ha Jun",
             "Park Do Yun", "Nguyen Minh Quan","Tran Chi Linh","Sato Ren","Takafumi Tsumugi","Seonwoo Eun Ha","Anis Amira",
             "Lam Van Khang", "Kagura Siro", "Slias Throne", "Mr.Justin", "Muhammad Adam", "Nurul Aisha","Ahmad Danial"]

PERSONALITY_CONFIG_POOL = { 
    "Normal" : {"patience" : (8,12), "scene_chance" : 0.05, "decay": 2, "weight": 70 },
    "Happy" : {"patience" : (13,17), "scene_chance" : 0, "decay": 3, "weight": 8 },
    "Sad" : {"patience" : (8,12), "scene_chance" : 0.03, "decay": 2, "weight": 8 },
    "Weird" : {"patience" : (4,8), "scene_chance" : 0.30, "decay": 1, "weight": 10 },
    "Angry" : {"patience" : (2,6), "scene_chance" : 0.70, "decay": 1, "weight": 4 },
                      }

DIALOGUE_POOL = { 
    "Normal" : {
        "borrow" :      ["Hi, I'd like to borrow a book please.",
                         "Excuse me, can I borrow this book?"],
        "return_book" : ["I'd like to return this book, thank you.",
                         "Here's the book I borrowed last week."],
        "fine" :        ["Oh, I have an overdue fine? How much is it?",
                         "Sorry, I forgot to return it on time."],
        "directions" :  ["Excuse me, where is the toilet?",
                         "Can you tell me where the reference section is?"],
        "scene" :       ["I've been waiting for so long!",
                         "This is taking too long, I want to speak to the manager."],
        "register" :    ["Hi, I'd like to get a library card please.",
                         "Can I register as a new member?"],
        "complaint" :   ["Excuse me, it's quite noisy here.",
                         "The books on that shelf are all mixed up."],
        "lost_book" :   ["I think I may have lost the book I borrowed...",
                         "I can't find the book anywhere, I'm so sorry."],
    },
    "Happy" : {
        "borrow" :      ["YAY! I found the book I wanted! Can I borrow this please? You're the BEST!",
                         "Hii!! Can I borrow this book? Thank you so much, you're amazing!!"],
        "return_book" : ["Here's the book! It was WONDERFUL, thank you for recommending it!!",
                         "Returning this! Hope you have a GREAT day, you deserve it!!"],
        "fine" :        ["Oh no, I have a fine? Of course I'll pay! Sorry for the trouble, my bad!!",
                         "Aiya, my fault la! Here's the money, keep the change, buy yourself a coffee!"],
        "directions" :  ["Excuse me, sorry to bother you! Could you please show me where the toilet is? Thank you SO much!!",
                         "Hi hi!! Where's the reference section? You're so helpful, I appreciate you!!"],
        "scene" :       ["Oh gosh, I'm so sorry for waiting so long, it must be busy today! Take your time!!",
                         "No rush no rush!! You're doing amazing, I can wait!!"],
        "register" :    ["YAY!! I'm so excited to get a library card!! This is the BEST day ever!!",
                         "Hi!! I want to register please!! Libraries are amazing and so are you!!"],
        "complaint" :   ["Um, sorry to say this, but it's a little noisy? But it's okay, you're all doing great!!",
                         "The books are a bit messy over there, but no worries, I can help tidy up if you want!!"],
        "lost_book" :   ["Oh no oh no oh no... I lost the book... I'm SO sorry, I feel terrible!!",
                         "I can't find the book anywhere... I'll pay for it, I promise!! I'm so sorry!!"],
    },

    "Sad" : {
        "borrow" :      ["...can I borrow this book? Sorry if I'm bothering you...",
                         "I just... want something to read. Does it even matter anymore..."],
        "return_book" : ["Here's the book... I didn't even finish it. Nothing feels right lately.",
                         "Returning this... sorry if it's a bit late. I forgot about everything."],
        "fine" :        ["A fine... okay. I'll pay. It's fine. Everything is fine.",
                         "Oh. Okay. How much? ...does it even matter."],
        "directions" :  ["Sorry... where is the toilet? Sorry for asking.",
                         "Excuse me... I've been walking around for a while. Where is the exit..."],
        "scene" :       ["I've been waiting for a long time... it's okay. I'm used to waiting.",
                         "Sorry... I don't mean to be a burden. I'll just... wait here."],
        "register" :    ["I want to register... my friend said I should get out more. So here I am.",
                         "Can I get a library card... I don't really know why I came here today."],
        "complaint" :   ["It's a bit noisy... I can't really think straight lately anyway.",
                         "The books are all mixed up... kind of like my life right now. Sorry."],
        "lost_book" :   ["I lost the book... I lose everything eventually.",
                         "It's gone. I looked everywhere. Story of my life, honestly."],
    },
    "Weird" : {
        "borrow" :      ["OI! Give me the book BRUH!", 
                         "Why is this taking so long?! I want borrow the book !"],
        "return_book" : ["HERE! Take your stupid book back!",
                         "I'm returning this, and it's YOUR fault it's late!"],
        "fine" :        ["WHAT FINE?! This is RIDICULOUS!",
                         "I am NOT paying this! Call your manager!"],
        "directions" :  ["WHERE IS THE TOILET?! WHY IS THERE NO SIGN?!",
                         "Can't you people put up proper signs?!"],
        "scene" :       ["I HAVE BEEN WAITING FOR ONE HOUR!!!",
                         "THIS LIBRARY IS A JOKE! I WANT TO SPEAK TO SOMEONE!"],
        "register" :    ["Just give me the card already, stop wasting my time!",
                         "Why do you need so much information just for a library card?!"],
        "complaint" :   ["This place is a MESS! How do you find anything?!",
                         "It's so noisy in here! Can't you control your customers?!"],
        "lost_book" :   ["Look, the book is gone. Deal with it.",
                         "I lost it, so what?! How much do I have to pay?!"],
    },
    "Angry" : {
        "borrow" :      ["OIII!! WOT ARE YOU DOIN' MATE !!",
                         "WHAT U DOING TAKE SO LONG TIME !! I WANT BORROW BOOKKK !!"],
        "return_book" : ["OIII!! HERE'S YOUR RUBBISH BOOK!! ",
                         "HERE!! TAKE YOUR RUBBISH BACK !! I DON'T WANT ITT!"],
        "fine" :        ["FINEE ? PUII!! NO MONEY !! ONLY ONE LIFE TO GIVE !!",
                         "I WONT PAY THE FINE!! THEN HOW?! COME AND FIGHT WITH ME!!"],
        "directions" :  ["WHEREE IS THEE TOILETT !!!" ,
                         "AUGHHH!!! BRING ME TO TOILETT!! MY BLADDER DAMN BURSTINGG!!"],
        "scene" :       ["I WANT TO FIRED YOU !! ASK YOUR DAMN MANAGER COME OUTT FASTTER !! NOW !!",
                         "SHITT PEOPLE SHITT PLACE SHITT EVERYWHERE!! ALLL AREE THEE FUCKINGG SHITTT!! "],
        "register" :    ["QUICK REGISTER MY ID ASSHOLE!! DONT WASTING MY TIMEEE!!",
                         "REGISTER MY ID NOWWWW !! YOU'RE SLOW AS HELLL LIKE YOUR DAMN GRANDMAA!!"],
        "complaint" :   ["THISS PLACE AND YOU ALL GUYS ARE REALLY SUCKKK !!",
                         "I HATEE THIS PLACE!!"],
        "lost_book" :   ["I LOST MY BOOK THEN HOW ?!! SO YOUR REAL MEAN HUH ?!!",
                         "I LOST THAT RUBBISH ANYMORE!! WHAT YOU GONNA DOO?!! TRY ME HUHH?!!"]
    },
}
GOODBYE_POOL = {
    "Normal" :  ["Thannk you so much, goodbye !","Thanks, see you next time ~","See you later"],
    "Happy" :   ["Thanks! bye-bye, have fun!","Goodbye, my friend! stay awesome!","HAHAHA! Hope you have a fun day! Bye!! "],
    "Sad" :     ["Thanks...,take care… goodbye...","Goodbye… I'll miss you", "Goodbye lah..., my heart pain sia"],
    "Weird" :   ["I'm a fool if i come back again..", "Bye? hehe..","Bye lah, nobodys like here..,hehe.."], 
    "Angry" :   ["I WONTT COME BACKK!!","THANKSS? GET LOSTT!!","I'LL HIT YOU IF I COME BACK AGAIN !!"],
}
NO_BOOK_INTENT_POOL = {
    "borrow" : {"weight" : 20},
    "directions" : {"weight" : 20},
    "register" : {"weight" : 20},
    "complaint" : {"weight" : 20},
    "scene" : {"weight" : 20},
}

HAS_BOOK_INTENT_POOL = {
    "return_book" : {"weight" : 80},
    "lost_book" : {"weight" : 20},
}